"""replaced username by name in User

Revision ID: e9128cde6b8a
Revises: cc9a76c22846
Create Date: 2024-11-01 13:34:18.459392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9128cde6b8a'
down_revision: Union[str, None] = 'cc9a76c22846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
